name: 'Terraform'

on: [pull_request]

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: create files
        run: touch a b c
      - name: TF Docs
        uses: Penson122/gh-actions@patch-1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
