name: 'Terraform'

on: [pull_request]

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-22.04
    steps:
      - name: create files
        run: touch 
      - name: TF Docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
